services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_URL:-task_management}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGPORT: ${PORT:-5432}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  # NestJS Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      DB_HOST: postgres
      PORT: ${PORT:-3000}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - postgres
    volumes:
      - ./dist:/usr/src/app/dist
    command: >
      sh -c "
        echo 'Waiting for PostgreSQL to be ready...' &&
        sleep 15 &&
        npm run migration:run &&
        npm run start:prod
      "

# Named volumes for data persistence
volumes:
  postgres_data:
    driver: local
